# Generated by Django 5.2.12 on 2026-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('store', '0002_rename_price_to_unit_price'),
        ('store', '0002_rename_price_to_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
